# Generated by Django 6.0.1 on 2026-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_REVIEW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pg_images/'),
        ),
    ]
