# Generated by Django 6.0.1 on 2026-02-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_REVIEW', '0002_pg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pg_gallery/')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PG_REVIEW.pg')),
            ],
        ),
    ]
