# Generated by Django 6.0.1 on 2026-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_REVIEW', '0003_pgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgimage',
            name='image',
            field=models.ImageField(upload_to='pg_images/'),
        ),
    ]
