# Generated by Django 6.0.1 on 2026-02-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_REVIEW', '0004_alter_pgimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('15', 'Within 15 Days'), ('30', 'Within 30 Days'), ('later', 'After 30 Days')], max_length=20),
        ),
        migrations.AddField(
            model_name='pg',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('bachelor_male', 'Bachelor Male'), ('bachelor_female', 'Bachelor Female'), ('company', 'Company')], max_length=30),
        ),
    ]
